---
global:
  use:
    -: "X doc"

packages:
  sys-apps/busybox-1.24.1: {}
  kern-module/mygpio: {}
  led-test/ledtest: {}
  
pre_install_commands:
  - "emerge --sync"
  - "chown -R portage:portage /usr/local/portage"
  - "echo 'PORTDIR_OVERLAY=\"/usr/local/portage ${PORTDIR_OVERLAY}\"' >> /etc/portage/make.conf"
  - "find /usr/local/portage -name \"*.ebuild\" -exec ebuild {} manifest \\;"

